### ISSUE TITLE
move contao-i18nl10n to friends of contao

### ISSUE THREAD

**Issue by MDevster** [exploreimpact/contao-i18nl10n#128]
Hey guys, what do you think about moving the extension to https://github.com/friends-of-contao and working together on one code base?

@markotodic @c3nj1 @LupusVII @erikherbert

**Comment by LupusVII** [comment]
Great idea :D
I've made a fork at https://github.com/Web-Ex-Machina/contao-i18nl10n
It's working on Contao 4.6 (but not on 4.7 yet).

Maybe it's better to move this one ? exploreimpact looks deserted.

**Comment by LupusVII** [comment]
I'm not used to moving repos to another account, what's the procedure for that ?
(I tried to move the repo but I'm not allowed to create a repository in friends-of-contao account)

**Comment by MDevster** [comment]
I would organize that we get a group there to maintain the repo. You will receive an invitation.

**Comment by ClaudioDeFacci** [comment]
Sorry for not replying to for such a long time. Had no time to care for the repo due to a way too high work load during the last few months.
I could simply add you as contributors I guess.
We could have a skype or Teamspeak call this weekend if you want to discuss the further development of this repo. Over here we just started to setup two new Contao projects that will require the repo, so my personal interest in the continuation of the development is back up.

**Comment by MDevster** [comment]
Sounds good, then let us work together on this repo

**Comment by LupusVII** [comment]
Hi folks !
I've made the release who merge all the work so far, to use the package through the Contao Manager again.
But it seems Packagist isn't updated automaticly. Can you update the webhook please ?
Thanks !

**Comment by ClaudioDeFacci** [comment]
Done :)
