### ISSUE TITLE
Wrong redirect to <language>/ on empty request (/)

### ISSUE THREAD

**Issue by ClaudioDeFacci** [exploreimpact/contao-i18nl10n#134]
If the website is accessed on root (i.e. www.example.tld/) the extension redirects to www.example.tld/{language} (where {language} is the user's language or the fallback language.
This is of cause a wrong behaviour in most cases.

The expected behaviour would be the one configured on the Contao backend's "Settings" page.

**Comment by ClaudioDeFacci** [comment]
Found the cause for the bug:
@LupusVII, you accidentially did not take into account the possibilities of different language parameter settings (s. tl_language for i18nl10n) in your recent work in "src/Hook/InitializeSystemHook.php".
Could you try to re-implement your solution so that other parameter configurations work aswell?
What was your initial reason for the redirect? Could you add some additional comments to your code?

Let me know if i could somehow help you with the fix. :)

**Comment by LupusVII** [comment]
@ClaudioDeFacci 
Totally, I'm sorry, it was a quickfix for an issue I had on a project that I pushed in release since I was alone at the time :/
I'll fix this later, these days are quite busy.

For the reason I make this : Using the domain.com/fr is the "good" way to use language in URL. The two others are not recommanded by the current practices when it comes to build friendly URLs, even if they work well.
In my point of view, we should only keep the {lang} fragment in URL and use domain.com/{lang}/ as root page of the current language. It's easier to understand, easier to keep updated :)

I'm sure you had your reasons to propose the 3 ways to handle languages. I'm curious to know if you already had a case where you couldn't use the domain.com/{lang}/ way.

**Comment by ClaudioDeFacci** [comment]
Yes, sounds good to only keep the /{lang}/ fragment.
We might consider that some people are using other solutions. But the "alias" solution is broken anyways, so... uhm...
Maybe a third opinion?

**Comment by ClaudioDeFacci** [comment]
I will start to fix and rework the extension as mentioned above this saturday.

**Comment by LupusVII** [comment]
Ok, I'm sorry, I'm extremely busy these days and I didn't take the time to fix this.
In May, I should be able to test your work and provide feedback :)

**Comment by ClaudioDeFacci** [comment]
Ok, perfect!

**Comment by ClaudioDeFacci** [comment]
I tried to fix the issue today without success.
There is currently no easy way to implement url without the alias of the main page attached to the language fragment.
To implement that feature I would recomment to:
1. Refactor the extension to only allow the language as URL fragment.
2. Document all the code more properly to ensure we fully understand the logic.
3. Create a ticket for the feature under which we solve it.

Under the branch #134 I disabled the redirect to the language fragment and hard wired the language parameter setting to "url". I will merge this hotfix now into master.

**Comment by LupusVII** [comment]
Actually, there is one way, but it's more a constraint than a way to implement it : the first page must have a / alias.
I do not like the way Contao handle roots page, we cannot have an empty request for "the home page" and it's quite wrong with SEO rules.
So maybe we can add a rule who'll understand the "{language}/" as root page in wanted language without redirect the user ?
