### ISSUE TITLE
Inline Scripts problem - does not include on translated pages

### ISSUE THREAD

**Issue by qbadev** [exploreimpact/contao-i18nl10n#81]
Contao 3.3.4, i18nl10n 1.5.3.
Website has 3 languages. German, English, Polish. Inline scripts do not show on any pages except German. I tried changing Caching Settings, Compressing Scripts settings and Minimize Source Code settings but without any reasonable results.
Looks like no inline scripts are included when non-first-language pages are displayed.

**Comment by patric-eberle** [comment]
Where did you define this 'inline scripts'? Themes > Layout > Custom JavaScript code?

**Comment by qbadev** [comment]
Inline scripts are used by Contao automatically, i.e. if I select Accordion JS in my template settings, Contao will attach inline accordion js code at the bottom of the HTML document. And it does not work well while using i18nl10n

**Comment by patric-eberle** [comment]
Are you sure this is caused by i18nl10n? I tested on 3.2.9 and 3.4.0 and was able to include/exclude all basic js from the layout options in all available languages. Since i18nl10n does not replace the building of the html page itself, it seems strange to me, that the module should have an impact. Maybe there is a conflict between modules?

**Comment by qbadev** [comment]
well, thanks for Your time. I double checked installed plugins, did some try-and-exclude on those plugins and found, that one extension was the cause. Sorry for disturbing. Extension is: RockSolid Custom Elements. I do not use it right now so I don't need to find out what exactly was the problem.
